# Generated by Django 5.0.3 on 2024-06-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_editattendance_delete_add_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editattendance',
        ),
    ]
