# Generated by Django 5.0.3 on 2024-06-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addattendance',
            name='totalhour',
        ),
    ]
