# Generated by Django 5.0.3 on 2024-06-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addattendance',
            name='totalhour',
            field=models.IntegerField(default=1),
        ),
    ]
