# Generated by Django 5.0.3 on 2024-06-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_addattendance_totalhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addattendance',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.status'),
        ),
    ]
