# Generated by Django 5.0.3 on 2024-06-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_add_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_attendance',
            new_name='addattendance',
        ),
    ]
