# Generated by Django 5.0.3 on 2024-06-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addattendance',
            name='status_id',
            field=models.CharField(choices=[('pending', 'pending'), ('ap_by_teacher', 'ap_by_teacher'), ('ap_by_tutor', 'ap_by_tutor'), ('ap_by_hod', 'ap_by_hod'), ('ap_by_princi', 'ap_by_princi'), ('ap_by_tutor_2', 'ap_by_tutor_2')], default='pending', max_length=15),
        ),
    ]
