# Generated by Django 5.0.2 on 2024-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_event_event_date_alter_hod_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=10),
        ),
    ]
