# Generated by Django 5.0.3 on 2024-06-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_addattendance_status_id_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
