# Generated by Django 5.0.3 on 2024-06-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_student_unique_reg_no_case_insensitive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='status',
        ),
    ]
